name: Build Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: nhan
          POSTGRES_PASSWORD: nhan
          POSTGRES_DB: nhan
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U nhan"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/nhan
          SPRING_DATASOURCE_USERNAME: nhan
          SPRING_DATASOURCE_PASSWORD: nhan
        run: mvn test
